name    'tapajos-ruby_stable'
version '1.0.1'
source  'https://github.com/tapajos/puppet-ruby-stable'
author  'Marcos Tapajos'
license 'Apache License 2.0'
summary 'Ruby stable module'
description 'Module to install ruby stable'
project_page 'https://github.com/tapajos/puppet-ruby-stable'
dependency 'puppetlabs/apt', '>= 1.1.0'